<template>
    <div>
        <img src="//m.360buyimg.com/mobilecms/s750x366_jfs/t1/68142/13/4285/242743/5d27eb37Ee11d66ba/9113667db702e328.jpg!cr_1125x549_0_72!q70.jpg.dpg" alt="" class="heading">

        <cube-form
            :model="model"
            :schema="schema"
            @submit="submitHandler">
        </cube-form>
    </div>
</template>

<script>
export default {
    data(){
        return{
            model:{
                username:'',
                password:''
            },
            schema:{
               fields:[{
                   //用户名配置
                   type:'input',
                   modelKey:'username',
                   label:'用户名',
                   props:{
                       placeholder:'请输入用户名'
                   },
                   rules:{
                       //校验规则
                       required:true,
                       type:'string',
                       min:3,
                       max:15
                   },
                   trigger:'blur',
                   messages:{
                       required:'用户名不能为空',
                       min:'用户名不能少于三个字符',
                       max:'用户名不能大于十五个字符'
                   } 
               },
               //密码配置
                {
                   type:'input',
                   modelKey:'password',
                   label:'密码',
                   props:{
                   placeholder:'请输入密码',
                   type:'password',
                   eye:{
                       open:false,
                   }   
                         },
                 rules:{
                     required:true,
                     type:'string',
                       min:3,
                       max:15
                 },
                 trigger:'blur',
                  },
                  //注册配置
                  {
                      type:'submit',
                      label:'注册'
                  }
               ] 
            }
        }
    },
    methods:{
        submitHandler(e){
            //阻止冒泡
            e.preventDefault()
           this.$http.get('/api/register',{params:this.model}).then(res=>{
               console.log(res.success)
           }).catch(err=>{
               console.log(err)
           })
        }
    }
}
</script>

<style lang="stylus" scoped>
    .heading
        height 150px
        width 100%
</style>